app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from kanon import views

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include('kanon.urls')),
    path('admin/', admin.site.urls),
]

app/kanon/urls.py
from django.urls import path

from . import views

app_name='api'

urlpatterns = [
    path('kanon/', views.index, name='index'),
    path('kanon/<int:kanon_id>/', views.detail, name='detail'),
    path('kanon/<int:kanon_id>/reservation', views.reservation, name='reservation'),
    path('kanon/<int:kanon_id>/order', views.order, name='order'),
    path('kanon/<int:kanon_id>/assignSoldier', views.assignSoldier, name='assignSoldier'),
    path('kanon/<int:kanon_id>/placeOrder', views.placeOrder, name='placeOrder'),
    path('user/createUser', views.createUser, name='createUser'),
    path('user/goToCreateUser', views.goToCreateUser, name= 'goToCreateUser'),
    path('kanon/createKanon', views.createKanon, name='createKanon'),
    path('kanon/goToCreateKanon', views.goToCreateKanon, name='goToCreateKanon')
]

app/kanon/models.py
from django.db import models

class Kanon(models.Model):
    kanon_name = models.CharField(max_length=200)
    munition = models.IntegerField(default=0)

    def __str__(self):
        return self.kanon_name

class User(models.Model):
    user_name = models.CharField(max_length=200)
    kanon = models.ForeignKey(Kanon, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user_name

app/kanon/views.py
from django.shortcuts import get_object_or_404, render, redirect

from django.http import HttpResponse

from .models import Kanon
from .models import User

def index(request):
    kanon_list = Kanon.objects.order_by('kanon_name')[:5]
    context = {'kanon_list': kanon_list}
    return render(request, 'kanon/index.html', context)

def detail(request, kanon_id):
    kanon = get_object_or_404(Kanon, pk=kanon_id)
    return render(request, 'kanon/detail.html', {'kanon': kanon})

# add users to kanon
def reservation(request, kanon_id):
    kanon = get_object_or_404(Kanon, pk=kanon_id)
    return render(request, 'kanon/manTheKanon.html',{'kanon': kanon})

# add munition to kanon
def order(request, kanon_id):
    kanon = get_object_or_404(Kanon, pk=kanon_id)
    return render(request, 'kanon/orderMunition.html',{'kanon': kanon})

def placeOrder(request,kanon_id):
    kanon = get_object_or_404(Kanon, pk=kanon_id)
    kanon.munition=kanon.munition+int(request.POST['amount'])
    kanon.save()
    return render(request, 'kanon/detail.html', {'kanon': kanon})

def assignSoldier(request,kanon_id):
    kanon = get_object_or_404(Kanon, pk=kanon_id)
    name = request.POST['name']
    user = User.objects.filter(user_name=name)
    if user:
        kanon.user_set.add(user[0])
    else:
        kanon.user_set.create(user_name=name)
    kanon.save()
    return render(request, 'kanon/detail.html', {'kanon': kanon})

def createUser(request):
    user_name = request.POST['name']
    user = User(user_name = user_name)
    user.save()
    return redirect('/api/kanon/')

def goToCreateUser(request):
    return render(request, 'user/user.html')


def createKanon(request):
    kanon_name = request.POST['name']
    kanon = Kanon(kanon_name = kanon_name)
    kanon.save()
    return redirect('/api/kanon/')

def goToCreateKanon(request):
    return render(request, 'kanon/kanon.html')

app/kanon/templates/kanon/detail.html
<h1>{{ kanon.kanon_name }}</h1>

<h3>users</h3>
<ul>
{% for user in kanon.user_set.all %}
    <li>{{ user.user_name}}</li>
{% endfor %}
</ul>

<form action="{% url 'api:reservation' kanon.id %}" method='post'>
    {% csrf_token %}
    <button type='submit'>reserveer soldaten</button>
</form>
    

<h3>munition</h3>
{{kanon.munition}}

<form action="{% url 'api:order' kanon.id %}" method='post'>
    {% csrf_token %}
    <button type='submit'>bestel munitie</button>
</form>

</br>
<form action="{% url 'api:index' %}" method="POST">
    {% csrf_token %}
    <button type="submit">back to index</button>
 </form>
    

app/kanon/templates/kanon/index.html
{% if kanon_list %}
    <ul>
    {% for kanon in kanon_list %}
        <li><a href="{% url 'api:detail' kanon.id %}">{{ kanon.kanon_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No kanons are available.</p>
{% endif %}

<form action="{% url 'api:goToCreateKanon' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Create Kanon</button>
 </form>

 <form action="{% url 'api:goToCreateUser' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Create User</button>
 </form>

app/kanon/templates/kanon/kanon.html
<!DOCTYPE html>
<html>
<body>

<h2>Create Kanon</h2>


<form action="{% url 'api:createKanon'%}" method='POST'>
    {% csrf_token %}
    <label for="name">Kanon name:</label><br>
    <input type="text" id="name" name="name"><br>
    <input type="submit" value="Create">
</form>
</br>
<form action="{% url 'api:index' %}" method="POST">
    {% csrf_token %}
    <button type="submit">back to index</button>
 </form>

</body>
</html>

app/kanon/templates/kanon/manTheCannon.html
<!DOCTYPE html>
<html>
<body>

<h2>MAN THE KANON!</h2>


<form>
    <label for="Kname">Konon name:</label><br>
    <input type="text" id="Kname" name="Kname"><br>
    <label for="Uname">User name:</label><br>
    <input type="text" id="Uname" name="Uname"><br>
    <input type="submit" value="Assign">
</form>


</body>
</html>

app/kanon/templates/kanon/manTheKanon.html
<!DOCTYPE html>
<html>
<body>

<h2>MAN THE KANON!</h2>


<form action="{% url 'api:assignSoldier' kanon.id %}" method='post'>
    {% csrf_token %}
    <label for="name">User name:</label><br>
    <input type="text" id="name" name="name"><br>
    <input type="submit" value="Assign">
</form>
</br>
<form action="{% url 'api:index' %}" method="POST">
    {% csrf_token %}
    <button type="submit">back to index</button>
 </form>
</body>
</html>

app/kanon/templates/kanon/orderMunition.html
<!DOCTYPE html>
<html>
<body>

<h2>Order Ammunition</h2>



<form action="{% url 'api:placeOrder' kanon.id%}" method='post'>
    {% csrf_token %}
    <label for="amount">Amount</label><br>
    <input type="number" id="amount" name="amount">
    <input type="submit" value="place Order">
</form>
</br>
<form action="{% url 'api:index' %}" method="POST">
    {% csrf_token %}
    <button type="submit">back to index</button>
 </form>
 
</body>
</html>

app/kanon/templates/munition/orderMunnition.html
<!DOCTYPE html>
<html>
<body>

<h2>Order Ammunition</h2>


<form>
    <label for="Aname">Ammunition type:</label><br>
    <input type="text" id="Aname" name="Aname"><br>
    <label for="amount">Amount:</label><br>
    <input type="number" id="amount" name="amount">
    <input type="submit" value="Order">
</form>


</body>
</html>

app/kanon/templates/user/user.html
<!DOCTYPE html>
<html>
<body>

<h2>Create User</h2>


<form action="{% url 'api:createUser'%}" method='POST'>
    {% csrf_token %}
    <label for="name">User name:</label><br>
    <input type="text" id="name" name="name"><br>
    <input type="submit" value="Create">
</form>

</br>
<form action="{% url 'api:index' %}" method="POST">
    {% csrf_token %}
    <button type="submit">back to index</button>
 </form>

</body>
</html>